name: Logaby
options:
  bundleIdPrefix: com.logaby
  deploymentTarget:
    iOS: "17.0"
  createIntermediateGroups: true
  developmentLanguage: en
  
settings:
  base:
    DEVELOPMENT_TEAM: 9Y9VC5568Q
    SWIFT_VERSION: "5.0"
    
targets:
  Logaby:
    type: application
    platform: iOS
    sources:
      - Logaby
    entitlements:
      path: Logaby/Logaby.entitlements
      properties:
        com.apple.security.application-groups:
          - group.com.logaby.shared
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.marcoslacayo.logaby
        INFOPLIST_FILE: Logaby/Info.plist
        CODE_SIGN_STYLE: Automatic
        MARKETING_VERSION: "1.0"
        CURRENT_PROJECT_VERSION: 1
        CODE_SIGN_ENTITLEMENTS: Logaby/Logaby.entitlements
    dependencies:
      - package: Supabase

packages:
  Supabase:
    url: https://github.com/supabase/supabase-swift.git
    from: 2.0.0

